version: "3.9"  # optional since v1.27.0
services:
  control:
    image: ansible-ubuntu-sshd:latest
    ports: 
      - "22"
    hostname: control
    networks:
      - ansible
    volumes:
      - .ssh:/root/.ssh
  managed1:
    image: ansible-ubuntu-sshd:latest
    ports:
      - "22"
    hostname: managed1
    networks:
      - ansible
    volumes:
      - .ssh:/root/.ssh
  managed2:
    image: ansible-ubuntu-sshd:latest
    ports:
      - "22"
    hostname: managed2
    networks:
      - ansible
    volumes:
      - .ssh:/root/.ssh
networks:
  ansible:
